version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: crispy_cookie_db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
